### ISSUE TITLE
bug in pipeline_stable_video_diffusion_controlnet.py

### ISSUE THREAD

**Issue by tan-jiaqi** [CiaraStrawberry/sdv_controlnet#27]
If line 502 of the [pipeline_stable_video_diffusion_controlnet.py  controlnet_condition = torch.cat([controlnet_condition] * 2) is not commented out in the training task , the following error will be reported

Loaded feature_extractor as CLIPImageProcessor from `feature_extractor` subfolder of ./stable-video-diffusion-img2vid-xt-1-1.                                                                                  | 1/5 [00:00<00:02,  1.61it/s]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.45it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/dell/PythonProjects/svd-temporal-controlnet/train_pose_controlnet_svd.py", line 1435, in <module>
[rank0]:     main()
[rank0]:   File "/home/dell/PythonProjects/svd-temporal-controlnet/train_pose_controlnet_svd.py", line 1368, in main
[rank0]:     video_frames = pipeline(
[rank0]:                    ^^^^^^^^^
[rank0]:   File "/home/dell/anaconda3/envs/SDBase/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/dell/PythonProjects/svd-temporal-controlnet/pipeline/pipeline_stable_video_diffusion_controlnet.py", line 538, in __call__
[rank0]:     down_block_res_samples, mid_block_res_sample = self.controlnet(
[rank0]:                                                    ^^^^^^^^^^^^^^^^
[rank0]:   File "/home/dell/anaconda3/envs/SDBase/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/dell/anaconda3/envs/SDBase/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/dell/anaconda3/envs/SDBase/lib/python3.11/site-packages/accelerate/utils/operations.py", line 820, in forward
[rank0]:     return model_forward(*args, **kwargs)
[rank0]:

**Comment by tan-jiaqi** [comment]
But during model inference, this line of code needs to be retained, very strange
